version: '3.7'

services:
  app:
    build: .
    ports:
     - "8085:8085"
    links:
      - redis
  redis:
    image: redis
    command: redis-server --save 60 1
    volumes:
      - data:/data
    ports:
     - "6379:6379"
    restart: always

volumes:
  data: